micronaut:
  application:
    name: helloWorld
datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: "jdbc:mysql://localhost:3306/USERSERVICE?autoreconnect=true"
  password: "root"
  username: ""
  testOnBorrow: true
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 30000
  validationQuery: SELECT 1
  max-active: 15
  max-idle: 10
  max-wait: 8000
flyway:
  url: jdbc:mysql://localhost:3306/hello_world
  user: "root"
  password: "root"
  baseline-on-migrate: true
